// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10.4.2025, 23:58:09
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/plugins/**/*.{js,ts,mjs}","/home/project/composables/**/*.{js,ts,mjs}","/home/project/utils/**/*.{js,ts,mjs}","/home/project/pages/index.vue","/home/project/pages/kontakt.vue","/home/project/pages/beratung.vue","/home/project/pages/impressum.vue","/home/project/pages/ueber-uns.vue","/home/project/pages/nutzer-agb.vue","/home/project/pages/datenschutz.vue","/home/project/pages/partner-agb.vue","/home/project/pages/ratgeber/index.vue","/home/project/pages/ratgeber/[slug].vue","/home/project/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/project/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/project/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;